### PR TITLE
Ron1 feature nxp 22732 integrate nuxeo package module

### PR DESCRIPTION
**Pull request by akervern**

### CODE REVIEW

**Comment by akervern** [comment]
👍

**Review by ron1 — CHANGES_REQUESTED** [review]
Don't we want the version lifecycle of nuxeo-sample-project to be out-of-band from the standard Nuxeo Platform versioning lifecycle just like is done for nuxeo-vision and all the marketplace packages? I chose version 9.4.2-SNAPSHOT so that the versioning does not collide with the current 9.3 versioning life-cycle. Thoughts?

**Comment by akervern** [comment]
@ron1 Yes we could, it is a common way when we want to separate lifecycles. But as `nuxeo-sample-project` is for learning and I'm would say that is not going to get changes that will require doing a new release on the same distribution, I would say that we can keep it like it to easily get the target distribution version.

Also, it is possible as you remove it from the add-ons pom (to prevent from a circular dependency: marketplace modules require distribution, that requires addon, that has a dependency on the core module...)

**Comment by ron1** [comment]
@akervern OTOH, nuxeo-sample-project is also a model for how Nuxeo users will develop/maintain their own custom addons. The lifecycle for user-developed addons will likely be much faster than the Nuxeo FT or LTS lifecycle. So, I recommend that the sample represent real-world development patterns rather than being overly simplified to ease learning. Just my POV.

**Comment by akervern** [comment]
Agreed, but I don't like that much to keep a version that looks like close to an hypothetical Nuxeo Version like `9.4.2`... 
Let's the devops team decide what would they prefer: @pgmillon @jcarsique, any idea?

**Comment by ron1** [comment]
Understood. The problem is that the version number must be > 9.3. Maybe 9.4 is too close to a real FT version. In that case, maybe 9.5 or 9.6 would be better since no FT release should ever fall between x.5 and x.9. Once FT/LTS versions reach 10.x, the 9.x version numbering will be less problematic.

**Comment by jcarsique** [comment]
Hi @ron1 , thanks for the PR!

A tiny practical remark: it would help the code review if the raw copy of files from https://github.com/nuxeo/nuxeo-marketplace-sample/ and their edit were isolated in two distinct commits. 
So, assuming the changes on those files were trivial, I only looked for other major changes, quickly passing over the version and new files hierarchy.

About the versioning question, I agree with both of you and I guess that we precisely have to find a solution satisfying both:
- the new resulting repository contains both a bundle (`JAR`) and a Nuxeo Package (`ZIP`). That is internally called "`a plugin repository`". It's not an official naming but let's use it here to distinguish from an `addon repo` containing *only* a Nuxeo Bundle and a `package repo` containing *only* a Nuxeo Package. This has an impact on the versioning constraints and the build order.
- as a `plugin repo`, it has its own versioning cycle and using the same as Nuxeo will be confusing. As well as jumping to an arbitrary `9.4.2-SNAPSHOT`.
- FYI, part of the confusion and complexity comes from the fact that we tried to cover the two use cases of internal and external development into one single project:
https://github.com/nuxeo/nuxeo-marketplace-sample/blob/master/pom.xml#L3
https://github.com/nuxeo/nuxeo-marketplace-sample/blob/master/pom.xml#L18-L20
https://github.com/nuxeo/nuxeo-marketplace-sample/blob/master/pom.xml#L37-L44
https://github.com/nuxeo/nuxeo-marketplace-sample/blob/master/pom.xml#L54-L82

For documentation and CI testing, we need to keep an `addon repo` and a `package repo`; and a new `plugin repo` is useful too. Here's a proposal:
- keep the two existing repositories, create a new plugin repository
- reference each other in their respective documentations
- double the samples to separate the two use cases: working on `org.nuxeo.*` material (aka "internal" or "core" dev) or working on `com.customer.*` material (aka "customer" dev).
- addon and package keep their current versions; the plugin will start from `1.0-SNAPSHOT`
- rename the plugin to `nuxeo-sample-plugin` and add it to marketplace.ini (additionally to the current `nuxeo-marketplace-sample`)

@akervern , can you handle all those changes please?

Also, we already talked about it but such a change highlights the need moreover: we should automate the generation of (part of) those samples in order to validate the consistency between the generator output and those hardcoded samples.

**Review by jcarsique — CHANGES_REQUESTED** [review]
see https://github.com/nuxeo/nuxeo-sample-project/pull/4#issuecomment-320983081

**Comment by ron1** [comment]
@jcarsique Your comments make sense and resolve the issues raised during our discussion.

If the plan is to maintain the nuxeo-marketplace-sample repo as is, can the "-nonxr" and "-explicit" package modules be left out of the new nuxeo-sample-plugin repo? If you agree they are relevant primarily to Nuxeo "internal dev" community only, do you think this makes sense?

Am I correct the "-plugin" suffix only appears for the new nuxeo-sample-plugin repo to distinguish it from the non-plugin (addon and package) repos? For other plugin repos, like nuxeo-vision, a "-plugin" suffix is unnecessary.

What is the criteria Nuxeo will use moving forward to determine whether a new internal project will be built w/separate addon/package repos or w/a single plugin repo?

Thanks.

**Comment by akervern** [comment]
@jcarsique make sense and it is a good idea.
Let's keep the "core" samples as it is, and I'll create a "customer" sample generated with CLI from a script.

@jcarsique also, I let you handle answer/close (I guess, from my understanding) the PRs and ticket. I'll do new ones for the new repository.

👍

**Comment by jcarsique** [comment]
Great, thanks @akervern 

@ron1 I'm glad you appreciate! Here are a few answers to your questions:

> If the plan is to maintain the nuxeo-marketplace-sample repo as is, can the "-nonxr" and "-explicit" package modules be left out of the new nuxeo-sample-plugin repo? 

Yes, since they are not the recommended way (state of the art) but demonstrations of other usages (with advantages and drawbacks), a unique sample of each is enough. Let's keep them in the nuxeo-marketplace-sample only.

> If you agree they are relevant primarily to Nuxeo "internal dev" community only, do you think this makes sense?

Actually, not only/not really for internal usage since I will track and harass whoever tries to do it at Nuxeo ;) but there are a few legitimate use cases.
Yes, we don't want to expose those hard-to-maintain alternate solutions too much.

> Am I correct the "-plugin" suffix only appears for the new nuxeo-sample-plugin repo to distinguish it from the non-plugin (addon and package) repos? For other plugin repos, like nuxeo-vision, a "-plugin" suffix is unnecessary.

You are correct. Note that the naming convention is useful but not strong enough, we will likely soon rely on a marker in the repository (or some parameter in the Jenkinsfile or a GitHub "topic" or...).

> What is the criteria Nuxeo will use moving forward to determine whether a new internal project will be built w/separate addon/package repos or w/a single plugin repo?

Hard to say: we like the theoretical simplicity of a single repo but often land at admitting that multiple repos are needed.
The main no-go is about using the same repository for storing unrelated stuff following uncorrelated lifecycles.
We want to increase teams and products autonomy and soft-coupling. So, the single "plugin" repo is the favorite. But the answer also depends on the technology (Java vs JS for instance).
I expect to see more "plugin" single repos in the future and less "addon + package" couple of repositories.

**Pull request closed without merging**
